### PR TITLE
missing variant object case transitions

### PR DESCRIPTION
**Pull request by disruptek**
I thought we caught all these but I've been carrying this patch for months now.  :slightly_frowning_face:

### CODE REVIEW

**Comment by SolitudeSF** [comment]
#4 deja vu. now i just want a race to see whoever's pr gets merged first if @zielmicha ever comes back to this.

**Comment by zielmicha** [comment]
I've missed the first PR. Which one is better :) ?

**Comment by SolitudeSF** [comment]
do you prefer `result` or implicit return?

**Comment by zielmicha** [comment]
Merged #4 instead of this.

**Pull request closed without merging**
